import Navigation from "@/components/navigation";
import { Metadata } from "next";
import "@/app/styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Movie",
    default: "Next Movie",
  },
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
